### ISSUE TITLE
Would like verbs to be able to override what the jobs are called in SummaryHandler

### ISSUE THREAD

**Issue by mikepurvis** [colcon/colcon-output#35]
I have an experimental verb which operates at the repo- rather than package level. It's working great, but it's too bad that the summary at the end of a run still refers to `n packages finished`, in this code (and elsewhere):

https://github.com/colcon/colcon-output/blob/a220a1cd27ec850e025a10224ca4c542c9fa7817/colcon_output/event_handler/summary.py#L74-L77

Not sure how much visibility this code and the running verb have into each other, but it would be nice if the `SummaryHandler` could somehow be passed a `singular/plural` tuple of what to refer to the jobs as.

**Comment by dirk-thomas** [comment]
I don't see how this kind of configuration could be passed around since there are numerous APIs involved in between.

Since this is all Python code how about enabling you to replace the word forms by e.g. replacing a function? I tried to add public API to enable that in #36. Please let me know if that suits your use case.
