### ISSUE TITLE
display the list of selected packages before starting building

### ISSUE THREAD

**Issue by mikaelarguedas** [colcon/colcon-output#8]
`ament` shows which packages will be built before starting building. It would be valuable to have the same in colcon.

It could be the default behavior or something that users can turn on with a flag.

**Comment by dirk-thomas** [comment]
I implemented an event handler for this which prints the package names in (flat) topological order: #12

Using a sequential executor this list makes sense since it shows what packages are being built in which order. But more common is the use of the parallel executor (the default when installed). In that case the actual order of processing will likely diverge from that printed list which might be more confusing to users than being helpful.

E.g. the topological order could be: `A, B, C` but the parallel executor might decide to first start `B` and afterwards `A` if e.g. `B` is being dependent on by `C` to get them unblocked as early as possible.

I am fine adding this new event handler (suggesting to be disabled by default) if others think this is useful. I am just concerned about potentially misleading the users.
